1
fintech-kotlin/cheglakov-cashback-service pull request #1
Opened 2020-02-22 19:37 UTC by navigator3228

# Выполнено задание №1

## В процесс было сделано:
 - Added cardNumber masking
 - Added Notification generator

## PR чеклист:
 - [ ] В Project выставлен `Tinkoff "Java to Kotlin"`
 - [ ] Добавлен label с номером домашнего задания

2020-02-25 08:46 UTC, KazakovIgor requested changes
Тест testGeneratingMessage должен проходить

2020-02-25 08:46 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        if (cardNumber === "") return ""
лучше воспользоваться встроенной функцией if (cardNumber.isEmpty()) return ""

2020-02-25 08:46 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/model/NotificationMessageInfo.kt
> +    val transactionDate: LocalDateTime = LocalDateTime.now()
Модель нужно использовать "как есть". Если понадобится доработать исходный код, в задании это будет явно указано

2020-02-25 08:46 UTC, KazakovIgor commented on build.gradle
> +    implementation "io.ktor:ktor-freemarker:$ktor_version"
Тянется очень много зависимостей, которые не используются
Достаточно
compile group: 'org.freemarker', name: 'freemarker', version: '2.3.29'

2020-02-25 08:46 UTC, KazakovIgor commented on src/test/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImplTest.kt
> +    fun testMaskingEmptyCardNumber() {
Название тестовых методов не нужно было менять

2020-02-25 08:46 UTC, KazakovIgor commented on src/test/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImplTest.kt
> +    fun testGeneratingMessage() {
Этот тест не проходит

2020-02-25 17:05 UTC, navigator3228 commented on build.gradle
> +    implementation "io.ktor:ktor-freemarker:$ktor_version"
Да)
экспериментировал со спрингом

2020-02-25 17:06 UTC, navigator3228 commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        if (cardNumber === "") return ""
Согласен

2020-02-25 17:06 UTC, navigator3228 commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        if (cardNumber === "") return ""
Согласен

2020-02-25 17:37 UTC, navigator3228 commented
> Тест testGeneratingMessage должен проходить

2020-02-26 07:14 UTC, KazakovIgor requested changes
Тест testGeneratingMessage должен проходить)

2020-02-26 07:14 UTC, KazakovIgor commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        if (cardNumber.length < end) return "################"
Если, например, понадобится изменить символ маскирования, в большом проекте можно не заметить этот хардкод. Лучше от него избавиться

2020-03-01 18:48 UTC, merged