Homework 3
fintech-kotlin/cheglakov-cashback-service pull request #3
Opened 2020-03-09 13:02 UTC by navigator3228

# Выполнено задание №

## В процесс было сделано:
 - ...
 - ...

## PR чеклист:
 - [ ] В Project выставлен `Tinkoff "Java to Kotlin"`
 - [ ] Добавлен label с номером домашнего задания

2020-03-10 15:34 UTC, dkotelnikov requested changes

2020-03-10 15:34 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/service/ProcessTransactionService.kt
> +    lateinit var cardServiceClient: CardServiceClient
Инъекция с помощью филда - не очень хорошая практика, лучше передать все параметры в конструктор. 
+ тогда не нужно будет использовать @Autowired + lateinit

2020-03-10 15:34 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/listener/TransactionListener.kt
> +    companion object {
Можно использовать просто:
`companion object: KLogging()`

2020-03-10 15:34 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/commons/annotation/Utils.kt
> +    companion object Factory {
👍 

Верный кейс для использования компаньонов, единственное - лучше не пересоздавать mapper каждый раз, а получать просто его инстанс.

+ как вариант, можно создать bean ObjectMapper

2020-03-10 15:34 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/client/ApacheHttpClientService.kt
> +class ApacheHttpClientService {
Кажется, что лучшим выходом будет создать класс конфигурации (@Configuration) и объявить там @Bean c HttpClient, который мы потом и будет инжектить по месту требования.

2020-03-10 18:32 UTC, navigator3228 commented on src/main/kotlin/ru/tinkoff/fintech/service/ProcessTransactionService.kt
> +    lateinit var cardServiceClient: CardServiceClient
А почему не очень хорошая практика?
Привык в джаве к соглашениям, что если в конструктор передается много параметров (как например тут 6), то не использовать его

2020-03-10 18:33 UTC, navigator3228 commented on src/main/kotlin/ru/tinkoff/fintech/client/ApacheHttpClientService.kt
> +class ApacheHttpClientService {
Не уверен. Ну понятно, что нежелательно каждый раз HttpClient пересоздавать, но мы же должны делать httpClient.close() после запроса, то есть бин этот не должен быть синглтоном.

2020-03-10 19:09 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/commons/annotation/NoArgAnnotation.kt
> +annotation class NoArgAnnotation
А зачем тебе noArg аннотация? 
Эта история - замена плагинам jpa noarg, которые уже должны быть установлены.
Ссылка на доку, где можно про это еще раз прочитать - https://kotlinlang.org/docs/reference/compiler-plugins.html#jpa-support

2020-03-11 14:37 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/service/ProcessTransactionService.kt
> +    lateinit var cardServiceClient: CardServiceClient
Это конечно тема для споров, но в контексе оверхэда котлина (@Autowired
    lateinit var) использование параметров выглядит более выигрышно. 
+ инъекция филдов, с точки зрения языка, не очень естественна, т.е. в отсутствии Spring'а такой код не заработает, а при использовании конструкторов дизайн становится более универсальным.

По этой ссылке описаны основные доводы в пользу использования конструктора - https://stackoverflow.com/questions/40620000/spring-autowire-on-properties-vs-constructor

2020-03-11 14:41 UTC, dkotelnikov commented on src/main/kotlin/ru/tinkoff/fintech/client/ApacheHttpClientService.kt
> +class ApacheHttpClientService {
Прошу прощения, флешбэки с restTemplate, который потокобезопасен (что позволяет использовать один экземпляр), его жизненный цикл остается полностью на откуп фреймворка, и беспокоится о ручном закрытии клиента не приходится.

2020-03-13 06:45 UTC, dkotelnikov approved these changes

2020-05-06 22:28 UTC, closed without merging